name: CD - Deploy con Git Pull

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configurar clave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H IP_DEL_SERVIDOR >> ~/.ssh/known_hosts
      - name: Hacer git pull en el servidor
        run: |
          ssh usuario@IP_DEL_SERVIDOR "
            cd ~/lemp-sites/m_lopez &&
            git pull origin main
          "

