name: CD - Deploy a Carpeta testJs (SSH directo)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurar SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Copiar archivos al servidor
        run: |
          scp -o StrictHostKeyChecking=no *.js ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/lemp-sites/m_lopez/testJs/

      - name: Verificar archivos
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            cd ~/lemp-sites/m_lopez/testJs
            ls -la
            echo '✅ Archivos copiados correctamente'
            echo 'ℹ️ Node.js no está instalado'
          "
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
