name: CD - Deploy a Carpeta testJs (SSH directo corregido)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurar SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copiar archivos
        run: scp -i ~/.ssh/id_rsa *.js ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/lemp-sites/m_lopez/testJs/

      - name: Verificar archivos
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            cd ~/lemp-sites/m_lopez/testJs
            ls -la
          "
