name: CD - Deploy con Git Pull

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Conectarse al servidor y hacer git pull
        run: |
          ssh -o StrictHostKeyChecking=no alumno@137.184.127.11 "
            cd ~/lemp-sites/m_lopez/testJs &&
            git pull origin main
          "
