name: CD - Deploy a Carpeta testJs

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Copiar archivos al servidor (testJs)
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}  # 137.184.127.11
          username: ${{ secrets.SSH_USER }}  # alumno
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "*.js"                # Copia solo math.js y math.test.js
          target: "~/lemp-sites/m_lopez/testJs/"
          rm: true                      # Opcional: elimina archivos antiguos

      - name: Verificar despliegue
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/lemp-sites/m_lopez/testJs
            ls -la                      # Verifica que los archivos llegaron
            node math.test.js           # Ejecuta pruebas en el servidor
